test_dbt_bigquery_elt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "ab-gcp-project"
      dataset: "test-dbt-bq"
      priority: interactive
      job_execution_timeout_seconds: 600
      threads: 4
      location: us
