version: '3'

services:
  airbyte-server:
    image: airbyte/airbyte:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - AIRBYTE_VERSION=latest

  airbyte-webapp:
    image: airbyte/webapp:latest
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - airbyte-server
